FROM python:3.7-alpine

RUN mkdir /api_test

COPY api_test.py /api_test/
COPY requirements.txt /api_test/

WORKDIR /api_test

RUN pip install -r requirements.txt

EXPOSE 5000

ENTRYPOINT ["pytest", "-s", "api_test.py"]